[Date]
date.timezone = "Asia/Tokyo"

[mbstring]
mbstring.language = "Japanese"

[PHP]
display_errors = On
display_startup_errors = On
max_execution_time = 30
memory_limit = 256M
post_max_size = 32M
upload_max_filesize = 32M
